name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --exclude-task=test

    - name: Archive build output
      uses: actions/upload-artifact@v1
      with:
        name: gradle-build
        path: build

    - name: Report annotations
      run: pwd

  inspect:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    container:
      image: mridang/intellijidea:2020.1

    steps:
      - name: Run in container
        run: find /__w
