name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: 'docker.pkg.github.com'
        username: 'mridang'
        password: 'a17a5db94d5f190cbecdd7aecff54a57284f3097'

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive code sniffing results
      uses: actions/upload-artifact@v1
      with:
        name: gradle-build
        path: build

    - name: Report annotations
      run: pwd

  inspect:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/mridang/docker-idea/intellijidea:2020.1
      volumes:
        - my_docker_volume:/app
    steps:
      - name: Run in container
        run: echo This job does specify a container.
