name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --exclude-task=test

      - name: Checkstyle
        uses: nikitasavinov/checkstyle-action@0.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
          checkstyle_config: ./config/checkstyle/checkstyle.xml

      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: gradle-build
          path: build
          