name: Intellij
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -PignoreCheckFailures=true

      - name: Run Intellij
        uses: mridang/action-idea@master
        with:
          target: .
          profile: ./.idea/inspectionProfiles/CI.xml
          output: ./output
          verbosity: v2
          scope: Inspection

      - name: Archive inspection results
        uses: actions/upload-artifact@v1
        with:
          name: inspection-results
          path: output
